In [28]:
import numpy as np
import tensorflow as tf

In [29]:
with open('reviews.txt','r') as f:
    reviews = f.read()
with open('labels.txt','r') as f:
    labels = f.read()
reviews[:2000]
labels[:100]


'positive\nnegative\npositive\nnegative\npositive\nnegative\npositive\nnegative\npositive\nnegative\npositive\nn'

In [30]:
from string import punctuation
all_text = ''.join([c for c in reviews if c not in punctuation])
reviews = all_text.split('\n')
all_text = ''.join(reviews)
words = all_text.split()
reviews[:3]

['bromwell high is a cartoon comedy  it ran at the same time as some other programs about school life  such as  teachers   my   years in the teaching profession lead me to believe that bromwell high  s satire is much closer to reality than is  teachers   the scramble to survive financially  the insightful students who can see right through their pathetic teachers  pomp  the pettiness of the whole situation  all remind me of the schools i knew and their students  when i saw the episode in which a student repeatedly tried to burn down the school  i immediately recalled          at           high  a classic line inspector i  m here to sack one of your teachers  student welcome to bromwell high  i expect that many adults of my age think that bromwell high is far fetched  what a pity that it isn  t   ',
 'story of a man who has unnatural feelings for a pig  starts out with a opening scene that is a terrific example of absurd comedy  a formal orchestra audience is turned into an insane  viol

In [31]:
from collections import Counter
counts = Counter(words)
vocab = sorted(counts, key=counts.get, reverse=True)
vocab_to_int = { word:i for i, word in enumerate(vocab,1)}
reviews_ints=[]
for r in reviews:
    reviews_ints.append([vocab_to_int[w] for w in r.split()])
print(reviews_ints[:3])

[[21025, 308, 6, 3, 1050, 207, 8, 2142, 32, 1, 171, 57, 15, 49, 81, 5831, 44, 382, 110, 140, 15, 5201, 60, 154, 9, 1, 4990, 5889, 475, 71, 5, 260, 12, 21025, 308, 13, 1980, 6, 74, 2405, 5, 613, 73, 6, 5201, 1, 25845, 5, 1983, 10341, 1, 5836, 1501, 36, 51, 66, 204, 145, 67, 1204, 5201, 20014, 1, 44669, 4, 1, 221, 883, 31, 2991, 71, 4, 1, 5807, 10, 687, 2, 67, 1501, 54, 10, 216, 1, 384, 9, 62, 3, 1408, 3703, 783, 5, 3488, 180, 1, 382, 10, 1213, 13953, 32, 308, 3, 349, 341, 2931, 10, 143, 127, 5, 7747, 30, 4, 129, 5201, 1408, 2334, 5, 21025, 308, 10, 528, 12, 109, 1452, 4, 60, 543, 102, 12, 21025, 308, 6, 227, 4176, 48, 3, 2215, 12, 8, 215, 23], [63, 4, 3, 125, 36, 47, 7567, 1395, 16, 3, 4187, 505, 45, 17, 3, 622, 134, 12, 6, 3, 1280, 457, 4, 1722, 207, 3, 10650, 7433, 300, 6, 667, 83, 35, 2119, 1088, 3000, 34, 1, 899, 67573, 4, 8, 13, 5123, 464, 8, 2666, 1722, 1, 221, 57, 17, 58, 796, 1299, 833, 228, 8, 43, 98, 123, 1470, 59, 147, 38, 1, 964, 142, 29, 667, 123, 1, 13989, 410, 61, 94, 177

In [32]:
# from sklearn import preprocessing
# le = preprocessing.LabelEncoder()
# le.fit(['positive','negative'])
# le.classes_
# lab = labels.split('\n')[:25000]
# labels = le.transform(lab)
# labels

labels = labels.split('\n')
labels = np.array([1 if each == 'positive' else 0 for each in labels])
labels

array([1, 0, 1, ..., 1, 0, 0])

In [33]:
review_lens = Counter([len(x) for x in reviews_ints])
print('zero length review:{}'.format(review_lens[0]))
print('maximum review length:{}'.format(max(review_lens)))

zero length review:1
maximum review length:2514


In [34]:
print(len(reviews_ints))
reviews_ints = [r for r in reviews_ints if len(r)>0]
print(len(reviews_ints))

25001
25000


In [35]:
seq_len = 200
features = np.zeros((len(reviews_ints),seq_len), dtype=int)
print(features.shape)
for i, row in enumerate(reviews_ints):
    features[i,-len(row):] = np.array(row)[:seq_len]
features[:3]

(25000, 200)


array([[    0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0, 21025,   308,     6,
            3,  1050,   207,     8,  2142,    32,     1,   171,    57,
           15,    49,    81,  5831,    44,   382,   110,   140,    15,
         5201,    60,   154,     9,     1,  4990,  5889,   475,    71,
            5,   260,    12, 21025,   308,    13,  1980,     6,    74,
         2405,     5,   613,    73,     6,  5201,     1, 25845,     5,
         1983, 10341,     1,  5836,  1501,    36,    51,    66,   204,
          145,    67,  1204,  5201, 20014,     1, 44669,     4,     1,
      

In [36]:
features[:1,:100]

array([[    0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0, 21025,   308,     6,
            3,  1050,   207,     8,  2142,    32,     1,   171,    57,
           15,    49,    81,  5831,    44,   382,   110,   140,    15,
         5201,    60,   154,     9,     1,  4990,  5889,   475,    71,
            5,   260,    12, 21025,   308,    13,  1980,     6,    74,
         2405]])

In [37]:
from sklearn.model_selection import train_test_split
split_frac = 0.8
lab = list(labels[:25000])
# print(type(lab))
# lab = labels.reshape(25001,-1)[:25000]
# print(features.shape, lab.shape)
train_x, val_x, train_y, val_y = train_test_split(features, lab, train_size=split_frac)
val_x, test_x, val_y, test_y = train_test_split(val_x, val_y, train_size=0.5)
print(train_x.shape, val_x.shape, test_x.shape)

(20000, 200) (2500, 200) (2500, 200)


In [38]:
# building graph

lstm_size = 256
lstm_layers = 1
batch_size = 500
learning_rate = 0.0001

In [39]:
n_words = len(vocab_to_int)

# Create the graph object
graph = tf.Graph()
# Add nodes to the graph
with graph.as_default():
    inputs_ = tf.placeholder(tf.int32, [None, None], name='inputs')
    labels_ = tf.placeholder(tf.int32, [None, None], name='labels')
    keep_prob = tf.placeholder(tf.float32, name='keep_prob')

In [40]:

# Size of the embedding vectors (number of units in the embedding layer)
embed_size = 300 

with graph.as_default():
    embedding = tf.Variable(tf.random_uniform((n_words, embed_size), -1, 1))
    embed = tf.nn.embedding_lookup(embedding, inputs_)

In [41]:
with graph.as_default():
    # Your basic LSTM cell
    lstm = tf.contrib.rnn.BasicLSTMCell(lstm_size)
    
    # Add dropout to the cell
    drop = tf.contrib.rnn.DropoutWrapper(lstm, output_keep_prob=keep_prob)
    
    # Stack up multiple LSTM layers, for deep learning
    cell = tf.contrib.rnn.MultiRNNCell([drop] * lstm_layers)
    
    # Getting an initial state of all zeros
    initial_state = cell.zero_state(batch_size, tf.float32)

In [42]:
with graph.as_default():
    outputs, final_state = tf.nn.dynamic_rnn(cell, embed,
                                             initial_state=initial_state)

In [43]:

with graph.as_default():
    predictions = tf.contrib.layers.fully_connected(outputs[:, -1], 1, activation_fn=tf.sigmoid)
    cost = tf.losses.mean_squared_error(labels_, predictions)
    
    optimizer = tf.train.AdamOptimizer(learning_rate).minimize(cost)

In [44]:

with graph.as_default():
    correct_pred = tf.equal(tf.cast(tf.round(predictions), tf.int32), labels_)
    accuracy = tf.reduce_mean(tf.cast(correct_pred, tf.float32))

In [45]:
def get_batches(x, y, batch_size=100):
    
    n_batches = len(x)//batch_size
    x, y = x[:n_batches*batch_size], y[:n_batches*batch_size]
    for ii in range(0, len(x), batch_size):
        yield x[ii:ii+batch_size], y[ii:ii+batch_size]

In [46]:
epochs = 10

with graph.as_default():
    saver = tf.train.Saver()

with tf.Session(graph=graph) as sess:
    sess.run(tf.global_variables_initializer())
    iteration = 1
    for e in range(epochs):
        state = sess.run(initial_state)
        
        for ii, (x, y) in enumerate(get_batches(train_x, train_y, batch_size), 1):
            feed = {inputs_: x,
                    labels_: y[:, None],
                    keep_prob: 0.5,
                    initial_state: state}
            loss, state, _ = sess.run([cost, final_state, optimizer], feed_dict=feed)
            
            if iteration%5==0:
                print("Epoch: {}/{}".format(e, epochs),
                      "Iteration: {}".format(iteration),
                      "Train loss: {:.3f}".format(loss))

            if iteration%25==0:
                val_acc = []
                val_state = sess.run(cell.zero_state(batch_size, tf.float32))
                for x, y in get_batches(val_x, val_y, batch_size):
                    feed = {inputs_: x,
                            labels_: y[:, None],
                            keep_prob: 1,
                            initial_state: val_state}
                    batch_acc, val_state = sess.run([accuracy, final_state], feed_dict=feed)
                    val_acc.append(batch_acc)
                print("Val acc: {:.3f}".format(np.mean(val_acc)))
            iteration +=1
    saver.save(sess, "checkpoints/sentiment.ckpt")

TypeError: list indices must be integers or slices, not tuple

In [ ]:
test_acc = []
with tf.Session(graph=graph) as sess:
    saver.restore(sess, tf.train.latest_checkpoint('/output/checkpoints'))
    test_state = sess.run(cell.zero_state(batch_size, tf.float32))
    for ii, (x, y) in enumerate(get_batches(test_x, test_y, batch_size), 1):
        feed = {inputs_: x,
                labels_: y[:, None],
                keep_prob: 1,
                initial_state: test_state}
        batch_acc, test_state = sess.run([accuracy, final_state], feed_dict=feed)
        test_acc.append(batch_acc)
    print("Test accuracy: {:.3f}".format(np.mean(test_acc)))